project:
  type: website
  output-dir: docs

website:
  title: "introduction-to-R"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Before we start"
        contents:
          - file-location.qmd
          - r-overview.qmd
      - section: "Install & prepare to work in R"
        contents:
          - install.qmd
          - rstudio-orientation.qmd
      - section: "Working in RStudio"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
      - section: "Importing datasets"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
      - section: "Manipulations of data"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
      - section: "Data visualization"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
      - section: "Analysis of complete datasets"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
format:
  html:
    theme: simplex
    css: styles.css
    toc: true



