project:
  type: website
  output-dir: docs

website:
  title: "Intro to R"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    number-sections: true
    contents:
      - section: "Introduction"
        contents:
          - file-location.qmd
          - r-overview.qmd
      - section: "Install & prepare to work in RStudio"
        contents:
          - install.qmd
          - rstudio-orientation.qmd
      - section: "Coding in R"
        contents:
          - basic-syntax.qmd
          - data-types.qmd
          - packages-libraries.qmd
      - section: "Importing datasets"
        contents:
          - importing-data.qmd
          - exporting-data.qmd
      - section: "Manipulations of data"
        contents:
          - tidyverse-intro.qmd
          - StarWars.qmd
          - Penguins.qmd
      - section: "Data visualization"
        contents:
          - basic-plots.qmd
          - customizatioms.qmd
          - advanced-dataviz.qmd
      - section: "Analysis of complete datasets"
        contents:
          - lab-microbiology.qmd
          - lab-oceanographic.qmd
          - lab-qualitativetable.qmd
format:
  html:
    theme: simplex
    css: styles.css
    toc: true



